//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGO.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Food
    {
        public int id { get; set; }
        public string Fname { get; set; }
        public string Date { get; set; }
        public string ResturantName { get; set; }
        public string Location { get; set; }
        public int Quantity { get; set; }
    }
}
